#ifndef DEFINES_H
#define DEFINES_H

#define MOVEMENT_SPEED 3.0f
#define SCR_WIDTH 800
#define SCR_HEIGHT 600

#define IS_INSTANCED true
#define BENCHMARK_ON false

#define MAX_BULLETS 100000
#define MAX_ENEMIES 1000

#define BULLET_SPEED 10.0f

#define SPAWNING_NEW_EMMITERS_AFTER_TIME 5.0f
#define BENCHMARK_SPAWNING_NEW_EMMITERS_AFTER_TIME 0.5f

#define AREA_RADIUS_SQ 2500.0f
#define PLAYER_AREA_RADIUS 10.0f
#define MAX_ANGLE_CHANGE_PER_SECOND 10.0f

#define PLAYER_ASSET_NAME "teapot"
#define EMMITER_ASSET_NAME "cube"
#define BULLET_ASSET_NAME "cube"

#endif